# The directory containing the source files to parse recursively
source:
  - ./src/assets/css
source_type:
  - .scss

# The directory that aigis will build to
dest: ./styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./src/styleguide/aigis_assets
  - ./dist/assets/css

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./src/styleguide/aigis_template
template_engine: ejs

 # compile log
log: true
